
CONFIG_USE_SEGGER_RTT=y
CONFIG_GNU_C_EXTENSIONS=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_ASSERT=y

CONFIG_SEGGER_RTT_SECTION_CUSTOM_DTS_REGION=y
CONFIG_SEGGER_RTT_SECTION_CUSTOM_NAME="segger_rtt_data"

CONFIG_MBOX=y
CONFIG_IPC_SERVICE=y
CONFIG_IPC_SERVICE_ICMSG=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

